$(document).ready(function(){
  $("#re").mouseenter(function(){
    $("#re").css("background-color","#0A0A0A");
  });
  $("#re").mouseleave(function(){
    $("#re").css("background-color","#333333");
  });
  $("#login").mouseenter(function(){
    $("#login").css("background-color","#0A0A0A");
  });
  $("#login").mouseleave(function(){
    $("#login").css("background-color","#333333");
  });
  $("#index").mouseenter(function(){
    $("#index").css("background-color","#0A0A0A");
  });
  $("#index").mouseleave(function(){
    $("#index").css("background-color","#333333");
  });
  $("#friends").mouseenter(function(){
    $("#friends").css("background-color","#0A0A0A");
  });
  $("#friends").mouseleave(function(){
    $("#friends").css("background-color","#333333");
  });
  $("#blog").mouseenter(function(){
    $("#blog").css("background-color","#0A0A0A");
  });
  $("#blog").mouseleave(function(){
    $("#blog").css("background-color","#333333");
  });
  $("#re").click(function(){
    window.location.href="re.html";
  });
  $("#login").click(function(){
    window.location.href="login.html";
  });
  $("#index").click(function(){
    window.location.href="/";
  });
  $("#friends").click(function(){
    window.location.href="/friends.html";
  });
  $("#blog").click(function(){
    window.location.href="http://www.tan90.info/blog/";
  });
});